version: '3.8'

services:
  postgres-db:
    image: postgres:15
    container_name: autores-db
    environment:
      POSTGRES_DB: autores-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: asdasd
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - autores-net

volumes:
  postgres_data:

networks:
  autores-net:
